# Header
menu:
- name: Archives
  path: /archives
  logo: archive
- name: Categories
  path: /categories
  logo: folder
- name: Tags
  path: /tags
  logo: tags
- name: Wiki
  path: /wiki
  logo: book
- name: About
  path: /about
  logo: user
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

pages:
- about
- wiki

wiki_dir: wiki
wiki_info:

# Sidebar
sidebar: right
home_widgets:
- search
- category
- tag
- archive
- blogroll
act_widgets:
- search
- recent_posts
- blogroll
post_widgets:
- nav
- post_date
- post_category
- post_tag

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:

links:
- name: Github
  url: https://github.com/sicongtang
  logo: github
- name: Google+
  url: https://plus.google.com/+BobbyTangSH
  logo: google-plus
- name: Linkedin
  url: http://cn.linkedin.com/pub/bobby-tang/43/3b9/a2
  logo: linkedin

feed:
  type: atom
  path: atom.xml
  limit: 20

sitemap:
  path: sitemap.xml
